### ISSUE TITLE
Executing the SAFE model on non-distributed mode.

### ISSUE THREAD

**Issue by bibhuti17** [Ouxiang-Li/SAFE#2]
##non-distributed mode
while trying to run the Ouxiang-Li/SAFE model on non-distributed mode the error is - "Default process group has not been initialized, please make sure to call init_process_group."

#complete description 
Not using distributed mode
Namespace(jpeg_factor=None, blur_sigma=None, mask_ratio=None, mask_patch_size=None, transform_mode='crop', batch_size=256, epochs=100, update_freq=1, model='SAFE', input_size=256, layer_decay_type='single', model_ema=False, model_ema_decay=0.9999, model_ema_force_cpu=False, model_ema_eval=False, clip_grad=None, weight_decay=0.05, lr=None, blr=0.0005, layer_decay=1.0, min_lr=1e-06, warmup_epochs=20, warmup_steps=-1, opt='adamw', opt_eps=1e-08, opt_betas=None, momentum=0.9, weight_decay_end=None, smoothing=0.1, mixup=0.0, cutmix=0.0, cutmix_minmax=None, mixup_prob=1.0, mixup_switch_prob=0.5, mixup_mode='batch', pretrained=True, global_pool=True, head_init_scale=0.001, model_key='model|module', model_prefix='', num_train=10000000000, data_path='', nb_classes=2, output_dir='/content/SAFE/checkpoint', log_dir=None, device='cuda', seed=None, resume='/content/SAFE/checkpoint/checkpoint-best.pth', eval_data_path='/content/drive/MyDrive/data/datasets/test5_DiTFake/test', imagenet_default_mean_and_std=True, data_set='IMNET', auto_resume=True, save_ckpt=True, save_ckpt_freq=5, save_ckpt_num=100, start_epoch=0, eval=True, dist_eval=True, disable_eval=False, num_workers=16, pin_mem=True, crop_pct=None, world_size=1, local_rank=-1, dist_on_itp=False, dist_url='env://', use_amp=False, distributed=False)
Number of params: 1.44M
Base lr: 5.00e-04
Actual lr: 5.00e-04
Accumulate grad iterations: 1
Effective batch size: 256
criterion = LabelSmoothingCrossEntropy()
Resume checkpoint /content/SAFE/checkpoint/checkpoint-best.pth
Eval only mode
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Test:  [0/1]  eta: 0:00:01  loss: 0.0506 (0.0506)  acc1: 1.0000 (1.0000)  time: 1.2281
Test: Total time: 0:00:01 (1.3580 s / it)
* Acc@1 100.00% loss 0.0506
Traceback (most recent call last):
  File "/content/SAFE/main_finetune.py", line 486, in <module>
    main(args)
  File "/content/SAFE/main_finetune.py", line 379, in main
    test_stats, acc, ap = evaluate(data_loader_val, model, device, val)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/SAFE/engine_finetune.py", line 177, in evaluate
    dist.all_gather(output_ddp, predictions)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2614, in all_gather
    default_pg = _get_default_group()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 977, in _get_default_group
    raise ValueError(
ValueError: Default process group has not been initialized, please make sure to call init_process_group.

#google colab notebook
trying to run this on colab notebook which has a single gpu so we are facing the error as mentoined above.
so is there any solution to this issue so that we can succesfully run this on google colab notebook.

**Comment by Ouxiang-Li** [comment]
Sorry for the confusion. In our practice, running on a single GPU only requires setting `GPU_NUM=1` with the distributed mode activated as well. Since we haven’t run it on Google Colab Notebook, we may not be able to provide effective suggestions as it is out of the environment problem.

**Comment by bibhuti17** [comment]
> Hi [@bibhuti17](https://github.com/bibhuti17) were you able to resolve this issue while working on google colab?

No, the issue isn't solved yet. Could you help?

**Comment by hardikbha** [comment]
No, I was also unable to run it on colab.....
